### ISSUE TITLE
Client not running on Mac

### ISSUE THREAD

**Issue by searledan** [GregHib/void-client#4]
Are they any fixes for running this client on Mac?

It freezes when using a pre-build client and building my own gets the below:

java: cannot find symbol
  symbol:   class Win32GraphicsDevice
  location: package sun.awt

**Comment by GregHib** [comment]
Looks like a Java version incompatability. You could try an older java version: https://support.apple.com/kb/DL1572?locale=en_GB

Related to this other Mac issue: https://rune-server.org/runescape-development/rs-503-client-and-server/informative-threads/586158-700-mac-issues.html

**Comment by searledan** [comment]
@GregHib Amazing, thank you for your help.
